version: '2'
services:
        kanboard:
                image: kanboard/kanboard:latest
                ports:
                        - "8080:80" #Connections to port 8080 are forwarded to port 80
                        - "4434:443" #Connections to port 4434 are forwarded to port 443
                volumes:
                        - kanboard_data:/var/www/app/data
                        - kanboard_plugins:/var/www/app/plugins
                        - kanboard_ssl:/etc/nginx/ssl
                environment:
                        DATABASE_URL: mysql://kanboard:kanboard-secret@db/kanboard
        db:
                image: mariadb:latest
                command: --default-authentication-plugin=mysql_native_password
                environment:
                        MYSQL_ROOT_PASSWORD: secret
                        MYSQL_DATABASE: kanboard
                        MYSQL_USER: kanboard
                        MYSQL_PASSWORD: kanboard-secret
volumes:
        kanboard_data:
        kanboard_plugins:
        kanboard_ssl:

