---
        - name: webmin SYS65
          hosts: webmin
          become: true
          vars:
                  install_utilities: true
                  firewalld_enable: true
          roles:
           - semuadmin.webmin
