---
# vars file for ansible-prometheus

# Internal vars, do not touch nor override

# https://prometheus.io/download/#prometheus
__prometheus_prom_bin_url: "https://github.com/prometheus/prometheus/releases/download"
__prometheus_am_bin_url: "https://github.com/prometheus/alertmanager/releases/download"
__prometheus_ne_bin_url: "https://github.com/prometheus/node_exporter/releases/download"
